### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by naittaleb** [romi/Scan3D#45]
- Machine learning pipe cannot run on middle GPU machines
 - Check if we can reduce graphical memory consumption

**Comment by naittaleb** [comment]
@Alienor134??

**Comment by Alienor134** [comment]
Piste: 
model.eval() in romiseg.utils.train_from_dataset.evaluation
or model.train()
test if gradients are computed (shouldn't be)

**Comment by jlegrand62** [comment]
ça ne change rien dans mon cas...

Voici l'erreur sans les modifs suggérées (j'ai le même résultat avec les modifs, les numeros de ligne changent):
```
DEBUG    [romiscan] cuda:0 used for images segmentation from fileConfig
DEBUG    [romiscan] Model name:Resnetdataset_gl_png_896_896_epoch50 from fileConfig
[...]
DEBUG    [romiscan] Image segmentation by the CNN from fileConfig
  0%|                                                                                                                                   | 0/72 [00:00<?, ?it/s]tensor(2.6226)
  1%|█▋                                                                                                                         | 1/72 [00:00<00:51,  1.37it/s]tensor(2.6226)
  3%|███▍                                                                                                                       | 2/72 [00:01<00:51,  1.37it/s]tensor(2.6226)
  4%|█████▏                                                                                                                     | 3/72 [00:01<00:37,  1.83it/s]tensor(2.6226)
  6%|██████▊                                                                                                                    | 4/72 [00:02<00:40,  1.69it/s]tensor(2.6400)
  7%|████████▌                                                                                                                  | 5/72 [00:03<00:43,  1.55it/s]tensor(2.6226)
  8%|██████████▎                                                                                                                | 6/72 [00:03<00:43,  1.53it/s]tensor(2.6400)
 10%|███████████▉                                                                                                               | 7/72 [00:04<00:43,  1.49it/s]tensor(2.6400)
 11%|█████████████▋                                                                                                             | 8/72 [00:05<00:43,  1.48it/s]tensor(2.6400)
 12%|███████████████▍                                                                                                           | 9/72 [00:05<00:42,  1.48it/s]tensor(2.6400)
 14%|████████████████▉                                                                                                         | 10/72 [00:06<00:42,  1.47it/s]tensor(2.6400)
 15%|██████████████████▋                                                                                                       | 11/72 [00:07<00:43,  1.41it/s]tensor(2.6400)
 17%|████████████████████▎                                                                                                     | 12/72 [00:08<00:43,  1.39it/s]tensor(2.6400)
 18%|██████████████████████                                                                                                    | 13/72 [00:08<00:42,  1.38it/s]tensor(2.6400)
 19%|███████████████████████▋                                                                                                  | 14/72 [00:09<00:42,  1.35it/s]tensor(2.6400)
ERROR    [luigi-interface] [pid 20100] Worker Worker(salt=888313286, workers=1, host=RDP-M7520-JL, username=jonathan, pid=20100) failed    Segmentation2D(output_file_id=out, scan_id=, dilation=1, binarize=True, threshold=0.01, upstream_task=ImagesFilesetExists, model_fileset=ModelFileset, model_id=Resnetdataset_gl_png_896_896_epoch50, query={"channel": "rgb"}, Sx=896, Sy=896, labels=[], inverted_labels=["background"], resize=True) from fileConfig
Traceback (most recent call last):
  File "/home/jonathan/miniconda3/envs/ugly_scan_0.6/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/home/jonathan/miniconda3/envs/ugly_scan_0.6/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/jonathan/Projects/ROMI/Scan3D/romiscan/tasks/proc2d.py", line 184, in run
    model_file, self.resize)
  File "/home/jonathan/Projects/ROMI/Segmentation/romiseg/Segmentation2D.py", line 101, in segmentation
    outputs = evaluate(inputs, model_segmentation)  #output image
  File "/home/jonathan/Projects/ROMI/Segmentation/romiseg/utils/train_from_dataset.py", line 546, in evaluate
    pred = model(inputs)
  File "/home/jonathan/miniconda3/envs/ugly_scan_0.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jonathan/Projects/ROMI/Segmentation/romiseg/utils/segmentation_model.py", line 114, in forward
    x = self.upsample(x)
  File "/home/jonathan/miniconda3/envs/ugly_scan_0.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jonathan/miniconda3/envs/ugly_scan_0.6/lib/python3.7/site-packages/torch/nn/modules/upsampling.py", line 131, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners)
  File "/home/jonathan/miniconda3/envs/ugly_scan_0.6/lib/python3.7/site-packages/torch/nn/functional.py", line 3013, in interpolate
    scale_factor_list[0], scale_factor_list[1])
RuntimeError: CUDA out of memory. Tried to allocate 392.00 MiB (GPU 0; 3.95 GiB total capacity; 1.12 GiB already allocated; 51.56 MiB free; 2.17 GiB reserved in total by PyTorch)
```

Paquets conda:
```
torch                     1.5.0                    pypi_0    pypi
torchfile                 0.1.0                    pypi_0    pypi
torchnet                  0.0.4                    pypi_0    pypi
torchvision               0.6.0                    pypi_0    pypi
```
